services:
  - type: web
    name: my-django-app
    env: python
    plan: starter
    region: oregon  # pick the closest region to you
    branch: main    # or your branch name
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn myproject.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        value: "your-secret-key"
      - key: DATABASE_URL
        value: "postgres://username:password@host:port/dbname"
databases:
  - name: aiml_db
    plan: free
